[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://www.bambooindustry.com"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://www.bambooflooringchina.com"

    [social.params]
        icon = "brand-twitter"
